package com.example.livemap.aux_files

val event_types = listOf(
    "🎨 Art",
    "🏸 Badminton",
    "🍺 Bar",
    "🏀 Basketball",
    "🎲 Board Games",
    "📚 Book Club",
    "🥐 Brunch",
    "🏕️ Camping",
    "🎬 Cinema",
    "🧗 Climbing",
    "☕ Coffee",
    "🎵 Concert",
    "🍳 Cooking",
    "🚴 Cycling",
    "💃 Dancing",
    "🍽️ Dinner",
    "🐕 Dog Walk",
    "🎪 Festival",
    "🎣 Fishing",
    "⚽ Football",
    "🎮 Gaming",
    "⛳ Golf",
    "🏋️ Gym",
    "🥾 Hiking",
    "🎤 Karaoke",
    "🛶 Kayaking",
    "🗣️ Language Exchange",
    "🏛️ Museum",
    "💼 Networking",
    "🎉 Party",
    "📷 Photography",
    "🧺 Picnic",
    "🍕 Pizza Night",
    "🏃 Running",
    "🛹 Skating",
    "⛷️ Skiing",
    "📖 Study Group",
    "🏄 Surfing",
    "🏊 Swimming",
    "🏓 Table Tennis",
    "🎾 Tennis",
    "🎭 Theatre",
    "✈️ Travel",
    "🏐 Volleyball",
    "🤝 Volunteering",
    "🍷 Wine Tasting",
    "🧘 Yoga"
)

val languages = listOf(
    "Albanian",
    "Amharic",
    "Arabic",
    "Basque",
    "Bengali",
    "Bosnian",
    "Bulgarian",
    "Cantonese",
    "Catalan",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Filipino",
    "Finnish",
    "French",
    "Galician",
    "German",
    "Greek",
    "Gujarati",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Korean",
    "Latvian",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Malay",
    "Maltese",
    "Mandarin Chinese",
    "Marathi",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Serbian",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tamil",
    "Telugu",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Welsh",
    "Yoruba"
)