package com.example.livemap

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.example.livemap.data.repository.FormState
import com.example.livemap.ui.auth.AuthViewModel

/**
 * Password recovery screen.
 *
 * Allows users to request a password reset email.
 *
 * Process:
 *   1. User enters their email address.
 *   2. Firebase sends a password reset email.
 *   3. The email contains a secure link generated by Firebase.
 *   4. The user chooses a new password through Firebase's recovery flow.
 *
 * On success:
 *   formState becomes Success and a confirmation message is displayed.
 *
 * On failure:
 *   formState becomes Error and the error message is shown.
 */
@Composable
fun ForgotPasswordScreen(
    onBackToLogin: () -> Unit,
    viewModel: AuthViewModel = viewModel()
) {

    // Observes the current form state (Idle, Submitting, Success or Error)
    // and automatically updates the UI whenever it changes.
    val formState by viewModel.formState.collectAsStateWithLifecycle()

    // Stores the email entered by the user.
    // remember keeps the value across recompositions.
    var email by remember { mutableStateOf("") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {

        // Screen title.
        Text(
            text = "Reset Password",
            fontSize = 32.sp,
            fontWeight = FontWeight.Bold
        )

        Text(
            text = "Enter your email address",
            fontSize = 14.sp,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Spacer(modifier = Modifier.height(32.dp))

        // Email input used to identify the account
        // that should receive the password reset email.
        OutlinedTextField(
            value = email,
            onValueChange = { email = it },
            label = { Text("Email") },
            singleLine = true,
            enabled = formState !is FormState.Submitting,
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(24.dp))

        // Sends a password reset request through Firebase Auth.
        Button(
            onClick = {
                viewModel.resetPassword(email)
            },
            enabled = formState !is FormState.Submitting,
            modifier = Modifier.fillMaxWidth()
        ) {

            // Displays a loading indicator while Firebase
            // processes the password reset request.
            if (formState is FormState.Submitting) {
                CircularProgressIndicator(
                    modifier = Modifier.height(20.dp),
                    color = MaterialTheme.colorScheme.onPrimary,
                    strokeWidth = 2.dp
                )
            } else {
                Text("Send reset email")
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        // Returns the user to the login screen.
        TextButton(
            onClick = onBackToLogin
        ) {
            Text("Back to Login")
        }

        // Confirmation message shown after Firebase successfully
        // sends the password reset email.
        if (formState is FormState.Success) {

            Spacer(modifier = Modifier.height(16.dp))

            Text(
                text = "Password reset email sent.",
                color = MaterialTheme.colorScheme.primary
            )
        }

        // Displays any validation or Firebase errors returned
        // during the password reset process.
        if (formState is FormState.Error) {

            Spacer(modifier = Modifier.height(16.dp))

            Text(
                text = (formState as FormState.Error).message,
                color = MaterialTheme.colorScheme.error
            )
        }
    }
}