package com.example.livemap.data.repository

import com.example.livemap.data.model.Event
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

/**
 * Single source of truth for the /events collection in Firestore.
 *
 * Design choice for v1 — we observe ALL events with one listener and let the
 * ViewModel partition them (nearby / joined / owned). This is fine while the
 * total number of events is small (academic project). At scale, we'd switch
 * to scoped queries (e.g. server-side filtering by location with geohash).
 */
class EventRepository(
    private val db: FirebaseFirestore = FirebaseFirestore.getInstance()
) {

    private val eventsCollection = db.collection("events")

    /**
     * Emits the full list of events whenever any of them change.
     * The list comes from the local cache first (offline support), then from
     * the server. Sorted by startAt descending (newest events first).
     */
    fun observeAllEvents(): Flow<List<Event>> = callbackFlow {
        val registration = eventsCollection
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    close(error)
                    return@addSnapshotListener
                }
                val events = snapshot?.documents
                    ?.mapNotNull { it.toObject(Event::class.java) }
                    ?: emptyList()
                trySend(events)
            }
        awaitClose { registration.remove() }
    }

    /** One-shot read of a single event. Used by EventDetailScreen later. */
    suspend fun getEvent(eventId: String): Result<Event?> = runCatching {
        eventsCollection.document(eventId).get().await()
            .toObject(Event::class.java)
    }

    /**
     * Creates a new event. The document ID is generated by Firestore and
     * stored back into the document via @DocumentId on read.
     */
    suspend fun createEvent(event: Event): Result<String> = runCatching {
        val newRef = eventsCollection.document()
        val data = mapOf(
            "name" to event.name,
            //"nameLower" to event.name.lowercase(),
            "description" to event.description,
            "ownerId" to event.ownerId,
            "dateTime" to event.dateTime,
            //"ownerName" to event.ownerName,
            //"ownerPhotoUrl" to event.ownerPhotoUrl,
            //"startAt" to event.startAt,
            //"endAt" to event.endAt,
            "locationText" to event.locationText,
            "locationLat" to event.locationLat,
            "locationLng" to event.locationLng,
            "geohash" to event.geohash,
            //"photoUrl" to event.photoUrl,
            "isPublic" to event.isPublic,
            "limitPeople" to event.limitPeople,
            //"participantsCount" to 0,
            "participantIds" to event.participantIds,
            "tags" to event.tags,
            //"languages" to event.languages,
            //"restrictions" to event.restrictions,
            //"itemsToBring" to event.itemsToBring,
            //"contactPhone" to event.contactPhone,
            //"contactInstagram" to event.contactInstagram,
            //"category" to event.category,
            //"ageRange" to event.ageRange,
            //"genderPref" to event.genderPref,
            "createdAt" to FieldValue.serverTimestamp(),
            "updatedAt" to FieldValue.serverTimestamp()
        )
        newRef.set(data).await()
        newRef.id
    }

    /**
     * Joins an event atomically: adds uid to participantIds AND increments
     * participantsCount. Using FieldValue operators ensures this works
     * correctly even with concurrent writes (no read-modify-write race).
     */
    suspend fun joinEvent(eventId: String, uid: String): Result<Unit> = runCatching {
        eventsCollection.document(eventId)
            .update(
                mapOf(
                    "participantIds" to FieldValue.arrayUnion(uid),
                    "participantsCount" to FieldValue.increment(1),
                    "updatedAt" to FieldValue.serverTimestamp()
                )
            )
            .await()
    }

    /** Mirror of joinEvent. arrayRemove is idempotent (removing twice is fine). */
    suspend fun leaveEvent(eventId: String, uid: String): Result<Unit> = runCatching {
        eventsCollection.document(eventId)
            .update(
                mapOf(
                    "participantIds" to FieldValue.arrayRemove(uid),
                    "participantsCount" to FieldValue.increment(-1),
                    "updatedAt" to FieldValue.serverTimestamp()
                )
            )
            .await()
    }
}