package com.example.livemap.data.repository

import com.example.livemap.data.model.User
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.SetOptions
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

/**
 * Handles the /users collection in the database.
 *
 * Document ID structure: /users/{uid} where {uid} == Firebase Auth uid.
 */
class UserRepository(
    private val db: FirebaseFirestore = FirebaseFirestore.getInstance()
) {

    // funnel every access through this CollectionReference to avoid conflicts ("user" - "users")
    private val usersCollection = db.collection("users")

    /**
     * Creates the user profile document right after a successful sign-up.
     * The uid is generated in the database, not in the client-side.
     *
     * Returns Result.success(Unit) | Result.failure(exception).
     */
    suspend fun createUserProfile(
        uid: String,
        email: String,
        displayName: String
    ): Result<Unit> = runCatching {
        val newUser = User(
            uid = uid,
            email = email,
            displayName = displayName,
            // Denormalize to lowercase for case-insensitive search.
            displayNameLower = displayName.lowercase(),
            // createdAt and updatedAt attributes will be generated by the server.
        )

        // map alongside the data class so FieldValue.serverTimestamp() can be added
        val data = mapOf(
            "email" to newUser.email,
            "displayName" to newUser.displayName,
            "displayNameLower" to newUser.displayNameLower,
            "description" to newUser.description,
            "sex" to newUser.sex,
            "photoUrl" to newUser.photoUrl,
            "languages" to newUser.languages,
            "hobbies" to newUser.hobbies,
            "location" to newUser.location,
            "phone" to newUser.phone,
            "instagram" to newUser.instagram,
            "createdAt" to FieldValue.serverTimestamp(),
            "updatedAt" to FieldValue.serverTimestamp()
        )

        usersCollection.document(uid).set(data).await()
    }

    // Reads a single user profile once. Returns null if the user doesn't exist.
    // Used for showing other users' profiles (friend's profile screen).
    suspend fun getUser(uid: String): Result<User?> = runCatching {
        val snapshot = usersCollection.document(uid).get().await()
        // toObject<User>() returns null if the document doesn't exist OR
        // if all its fields fail to map (e.g. document is empty).
        snapshot.toObject(User::class.java)
    }

    // Emits the user document every time it changes on the server (or in the local cache).
    // Used by the Profile screen to show your own data, and to react to user's profile changing.
    // Emits null if the document is deleted or doesn't exist.
    fun observeUser(uid: String): Flow<User?> = callbackFlow {
        val registration = usersCollection.document(uid)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    close(error)
                    return@addSnapshotListener
                }
                // snapshot is null only if the listener was removed.
                val user = snapshot?.toObject(User::class.java)
                trySend(user)
            }

        awaitClose { registration.remove() }
    }

    /**
     * Updates one or more fields of the user document.
     * The 'updates' map can contain only the fields that changed:
     *   updateUser(uid, mapOf("description" to "new bio"))
     */
    suspend fun updateUser(uid: String, updates: Map<String, Any?>): Result<Unit> = runCatching {
        // Always bump updatedAt — never let callers forget to set it.
        val withTimestamp = updates + ("updatedAt" to FieldValue.serverTimestamp())
        usersCollection.document(uid).set(withTimestamp, SetOptions.merge()).await()
    }

    // Wrapper for the common case of renaming.
    // Guarantees that displayName and displayNameLower stay in sync
    suspend fun updateDisplayName(uid: String, newName: String): Result<Unit> =
        updateUser(
            uid,
            mapOf(
                "displayName" to newName,
                "displayNameLower" to newName.lowercase()
            )
        )
    /**
     * Emits the full list of users whenever any of them changes.
     * Sorted by displayName (case-insensitive).
     *
     * Used by FriendsScreen to populate "Suggested for you" — anyone who
     * isn't the current user and isn't already a friend or blocked.
     *
     * Scalability note: this reads ALL users. Fine for an academic project
     * with dozens of users; would need pagination for hundreds+.
     */
    fun observeAllUsers(): Flow<List<User>> = callbackFlow {
        val registration = usersCollection.addSnapshotListener { snapshot, error ->
            if (error != null) {
                close(error); return@addSnapshotListener
            }
            val users = snapshot?.documents
                ?.mapNotNull { it.toObject(User::class.java) }
                ?.sortedBy { it.displayNameLower }
                ?: emptyList()
            trySend(users)
        }
        awaitClose { registration.remove() }
    }
}